name: Node Continuous Integration

on:
  pull_request:
<<<<<<< HEAD
    branches: [ master ]
=======
    branches: [ main ]
>>>>>>> e4bd3f0f47753a38bb65159e73345544e9fef0b2


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
<<<<<<< HEAD
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build
=======
          node-version: 23
      - run: npm ci
      - run: npm test
      - run: npm run build
>>>>>>> e4bd3f0f47753a38bb65159e73345544e9fef0b2
